### ISSUE TITLE
HTLC API methods with paging support do not return total count

### ISSUE THREAD

**Issue by KingGorrin** [Big-Inches-Club-House/bich#8]
The `getHtlcInfosByTimeLockedAddress` and `getHtlcInfosByHashLockedAddress` HTLC API methods support paging but do not return the total count. The other API methods that support paging return a separate object containing the results and the total count. The total count is usefull for calculating the total page count for example.

**Comment by KingGorrin** [comment]
Thought I was added the issue to the go-zenon repository. Which doesn't seem to have issues activated.

**Comment by georgezgeorgez** [comment]
Oh wow I just saw this, even after you dm'd me haha. Let me see about enabling issues. I think it might not be possible for forks to have their own issues.
